### ISSUE TITLE
Build for offline use

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt-community/vuetify-module#108]
**Is your feature request related to a problem?**
I would like to offer my app as offline-working webapp. This requires me to have the icons and fonts load locally.

**Describe the solution you'd like**
make the module configurable for the online resources to use modules instead.

**Describe alternatives you've considered**
set up vuetify manually again instead of using the module

**Comment by kevinmarrec** [comment]
@MartinMuzatko You can already do it, it is supposed to be handle by the user if you need to do implement icons/fonts on your own.

You just have to set https://github.com/nuxt-community/vuetify-module#defaultassets to `false` as mentionned in the option description (last line).

This module uses online resources by default so that users can directly play with the Vuetify framework. You can skip that with the option, and implement your own local font & icons through Nuxt configuration (probably 

Then for icons you can have a look for https://vuetifyjs.com/en/customization/icons#install-material-design-icons-js-svg, it works well to only bundle some Material SVG icons :)

And if you're wondering how to use fonts locally :
https://answers.themler.io/articles/9064/how-to-use-google-fonts-locally

There are plenty of different fonts and plenty of icons fonts existing, so such feature request is out of the scope of the module.

**Comment by MartinMuzatko** [comment]
thank you a lot for the quick response!
I will try that :) 

Yes a little documentation on how to make it offline capable would be great :)

**Comment by kevinmarrec** [comment]
@MartinMuzatko I updated docs : https://github.com/nuxt-community/vuetify-module#offline-applications 😉

**Comment by waspinator** [comment]
Thanks @kevinmarrec I was able to get fonts to work, but I'm not sure how to get icons to work correctly. I downloaded the icon package from https://materialdesignicons.com, which I think is the default icon set used in vuetify, copied it to static directory, and added the included css file to the `Global CSS` configuration section of `nuxt.config.js`

      css: [
           '@/static/fonts/material-design-icons/css/materialdesignicons.min.css'
       ]

But the icon names aren't the same as what are in Vuetify examples. For example to get a map marker I need to use `mdi-map-marker` instead of `place`. 

What font should I use to get the default icon set?
