### ISSUE TITLE
vuetify v2.0.7 release, update please

### ISSUE THREAD

**Issue by ksbgenius** [nuxt-community/vuetify-module#113]
vuetify v2.0.7 release, update please

**Comment by kevinmarrec** [comment]
@ksbgenius 

New version will be published tomorrow but you can still remove and reinstall `@nuxtjs/vuetify` dependency, it should make it installed with Vuetify 0.2.7.

**Comment by lyonsbp** [comment]
@kevinmarrec Are you saying that whenever Vuetify updates, if we delete our lockfile and reinstall `@nuxtjs/vuetify` that the newest Vuetify patch version will be brought in always? 

Just to make sure I am understanding correctly. Otherwise, it might be worth looking into setting Vuetify as a peer dependency, and leave it up to the user to have a Vuetify version installed. Somethings just feels a little "off" that I have to reinstall this entire package when an unrelated package (Vuetify) does a patch update.

**Comment by marcusaaronb** [comment]
I think vuetify not stable version 2.0.*

**Comment by ianfortier** [comment]
> @ksbgenius
> 
> New version will be published tomorrow but you can still remove and reinstall `@nuxtjs/vuetify` dependency, it should make it installed with Vuetify 2.0.7 (It's about lock file maintenance, you can also remove `yarn.lock` and redo `yarn install`)

No it's not working

**Comment by kevinmarrec** [comment]
@lyonsbp @ianfortier 

It's something called `lock file maintenance`.
@ianfortier yes it is working

Nuxt module targets `^2.0.5`, it resolves to last patch (or maybe minor) version.
In our current case : `2.0.7`


![image](https://user-images.githubusercontent.com/25272043/63119090-93176500-bf9f-11e9-9155-40cf666b59a8.png)

**Comment by ianfortier** [comment]
> @lyonsbp @ianfortier
> 
> It's something called `lock file maintenance`.
> @ianfortier yes it is working
> 
> Nuxt module targets `^2.0.5`, it resolves to last patch (or maybe minor) version.
> In our current case : `2.0.7`
> 
> ![image](https://user-images.githubusercontent.com/25272043/63119090-93176500-bf9f-11e9-9155-40cf666b59a8.png)

Maybe its because I'm using NPM, but I got the same issue with the theme overwriting the 2.0.7 is supposed to fix

`"vuetify": {
      "version": "2.0.7",
      "resolved": "https://registry.npmjs.org/vuetify/-/vuetify-2.0.7.tgz",
      "integrity": "sha512-dnW6VowHOXaq6cxYjn6RXcTWVCJnWh3ajh4e4pP84grb4Smebka6yUQSG8rSalPyFzkPeNGuXrXWVsbTAIqv7w=="
    },`

`"@nuxtjs/vuetify": {
      "version": "1.2.1",
      "resolved": "https://registry.npmjs.org/@nuxtjs/vuetify/-/vuetify-1.2.1.tgz",
      "integrity": "sha512-oDiL6O1LSyiwSDs2hVZ7rwM9KMht/yPYDMhdOL+oP3RWCfcsgk2kYZrbFNKf23U5ZVzVDVjwbDX/hFOno/F7QA==",
      "requires": {
        "deepmerge": "^4.0.0",
        "fibers": "^4.0.1",
        "sass": "^1.22.9",
        "sass-loader": "^7.1.0",
        "vuetify": "^2.0.5",
        "vuetify-loader": "^1.3.0"
      }`

**Comment by kevinmarrec** [comment]
@ianfortier It's not fixed, it has been "fixed" in 2.0.6 and reverted in 2.0.7 cause it broke all Vue CLI projects using vue-meta.

If you're using SPA mode, issue is still here, and that's why issues are still open in this repo.

I was in vacations and just back to home, I'm releasing new version with 2.0.7 but still need to dive again in more testing to find the SPA fix that won't break everything around Vuetify.

**Comment by lyonsbp** [comment]
I appreciate the clarification @kevinmarrec 

Does having the Vuetify version tied to this package though not seem weird at all? Like I am thinking, when Vuetify 2.1.x eventually launches, will you start maintaining a branch of this package that has the latest Vuetify 2.0.x version, but also has any bug fixes for this package itself?

Sorry if that is not clear, I just wanted to try and understand the reasoning for tying the Vuetify version to this package, since it is just a loader/tooling package and really seems weird to me.

**Comment by kevinmarrec** [comment]
When Vuetify 2.1.x launches, it will be first just a patch version of the Nuxt module that ships 2.1.x.
If it's not anymore a peerDependency it's for 2 reasons :
- Nuxt module being now a devDependency, any direct dependency won't have impact on production ready environments so it doesn't have drawbacks.
- Just having to add the module and nothing else feels simpler for new comers (DX)

**Comment by lyonsbp** [comment]
Alright, I can see that second reason being good for DX for newcomers. I just could see issues arising potentially where some project/org needs a specific version of vuetify that is not in this package, and would then have to "eject" and manually setup the Vuetify library. 

Just food for though, I appreciate your responses!

**Comment by kevinmarrec** [comment]
@lyonsbp Not sure about this "specific version" need.
Further Vuetify versions are supposed to be only bug fixes and new features, nothing will be breaking until Vuetify 3.0.
