### ISSUE TITLE
Fixed dependency version

### ISSUE THREAD

**Issue by paulvonber** [nuxt-community/vuetify-module#145]
**Is your feature request related to a problem? Please describe.**
Vuetify releasing minor versions quiet often with lot of changes and pretty bugy  

**Describe the solution you'd like**
I would suggest to have fixed version number for vuetify debendency i.e. "vuetify": "2.0.11", as every time you pull you get updates you probably you don't want from the latest version, it's pretty hard later to find a problems when they come "out of nowhere"

**Comment by ianfortier** [comment]
> From https://github.com/nuxt-community/vuetify-module/issues/113#issuecomment-521151016 : you can still remove and reinstall @nuxtjs/vuetify dependency, it should make it installed with Vuetify 2.0.7 (It's about lock file maintenance, you can also remove yarn.lock and redo yarn install)

**Comment by johnleider** [comment]
@paulvonber Could you elaborate? The last minor version we released was over 8 months ago for v1.5.

**Comment by paulvonber** [comment]
@johnleider my mistake probably not a minor version, but build version (last digits however you call them :) ) so when @nuxtjs/vuetify has dependency written like: "vuetify": "^2.0.10" and you run yarn/npm install it always pull latest vuetify version even if it's dependency is "2.0.10" it pulls the latest one like 2.0.12. 
For example 2.0.10 was all good, but 2.0.11 introduced [this problem](https://github.com/vuetifyjs/vuetify/issues/8815) so for production builds that's a bit risky, and overall you can't revert to the older version while using @nuxtjs/vuetify the only way now to have fixed dependency, is to add another line like "vuetify": "2.0.10" to packages.json

**Comment by kevinmarrec** [comment]
@paulgv I think keeping last version is fine cause it always ships multiple fixes.
If something goes wrong around a patch version of a dependency, it's not our job (nuxt module maintainer) to do something, it's the dependency that has to quick patch release if the issue is critical.

If you want I can make it pinned to last patch version (tilted range `~2.0`) if you're afraid that something may be buggy around minor versions.

Also, ultimately there is a solution that consist to update manually your lock file so it matches the version you want. Then clean/reinstall dependencies.
