### ISSUE TITLE
V-spacer does not work in v-app-bar during production mode

### ISSUE THREAD

**Issue by snorreks** [nuxt-community/vuetify-module#165]
**Module version**
Version 1.8.3
**Describe the bug**
When I use run Nuxt in dev mode, the v-spacer works as intended in the v-app-bar. But when I run Nuxt in production mode the v-spacer does not work in the v-app-bar. There is no error and this was not a issue before vuetify 2.

`  <v-app-bar dense fixed clipped-left app floating elevate-on-scroll>
    <v-app-bar-nav-icon @click="changeSideBar"></v-app-bar-nav-icon>
    <v-toolbar-title @click="$router.push('/')">
      <img src="~/assets/images/logo/logo-text.png" alt="Vuetify.js" height="36" width="200" />
    </v-toolbar-title>
    <v-spacer />
        <v-icon>mdi-settings</v-icon>
  </v-app-bar>`

**Expected behavior**
Want to have the settings icon to the right of the v-app-bar.
**Screenshots**
In debug mode:
![image](https://user-images.githubusercontent.com/36089469/64909149-b5b8ad00-d708-11e9-88b9-5c60f016a2a7.png)
In production mode:
![image](https://user-images.githubusercontent.com/36089469/64909154-cf59f480-d708-11e9-8aa6-4bd90789b827.png)

**Comment by kevinmarrec** [comment]
@snorreks **VSpacer** is intended to be used within **VRow** from Vuetify [Grid system](https://vuetifyjs.com/en/components/grids).

To achieve your spacing within your app bar, you need to use :
```html
<div class="flex-grow-1"></div>
```
instead of
```html
<v-spacer />
```

You can check [code of pre-made layouts](https://vuetifyjs.com/en/getting-started/pre-made-layouts) that use this behavior.
