### ISSUE TITLE
Vuetify size is too large

### ISSUE THREAD

**Issue by Shivk355** [nuxt-community/vuetify-module#199]
Vendor size getting too large after using @nuxt/vuetify 1.9.0 even in treeshaking mode.
How to reduce vuetify size in production

**Comment by kevinmarrec** [comment]
@Shivk355 Probably cause you have CSS bundle in JS file, you can try `build.extractCSS: true` in Nuxt options, it will separate Vuetify JS & CSS. The CSS is by default kind of huge, but really smaller when using gzip in production.

Otherwise, it's not something that can be discussed around this module, this module only registers Vuetify to make developer experience better, it doesn't add extra things that will make bundle larger, so you may ask for help on Vuetify Discord OR Vuetify repository.

**Comment by Shivk355** [comment]
build.extractCSS: true, resolves the issue for me.

Thanks a lot for the help.
