### ISSUE TITLE
I want to introduce a style sheet from CDN

### ISSUE THREAD

**Issue by snoopy83101** [nuxt-community/vuetify-module#214]
I want to introduce a style sheet from CDN

This speeds up and saves traffic.

Configured in nuxt.confg
   Modules: ['@nuxtjs/vuetify'],

It seems that the style sheet can only be referenced from node-modules.
Is there any way to solve it?

**Comment by snoopy83101** [comment]
i know 
head(){
  return
       ......
}

But this will introduce css files from two places.
What do I want to refuse to reference node_modules?

**Comment by kevinmarrec** [comment]
@snoopy83101 Treeshaking should make less used CSS than using the whole Vuetify CSS one, so I don't really understand what you're trying to do. Is it working fine when referenced from `node_modules` ? Cause It's totally fine sometimes to link stylesheets that are in one of your dependencies (`~vuetify/` instead of `node_modules/vuetify/` may work as well)

**Comment by snoopy83101** [comment]
"Treeshaking should make less used CSS than using the whole Vuetify CSS one"

but "using the whole Vuetify CSS one ", Can go for free public CDN

**Comment by kevinmarrec** [comment]
You can't have the good of both worlds, at least with current Vuetify component implémentation. You can either load full js and full CSS through dans. But cannot treeshaking js and serve CSS with CDN. The css is bundled inside the JS around Vuetify when using tree shaking

**Comment by snoopy83101** [comment]
I think I understand.
I will continue to use it, thank you very much for your answer.
