### ISSUE TITLE
How to override $headings Sass variables by variables.scss?

### ISSUE THREAD

**Issue by sktbcbbs** [nuxt-community/vuetify-module#317]
**Module version**
1.11.2

**Describe the bug**
Cannot override Sass variable "$headings"

**To Reproduce**
https://github.com/sktbcbbs/nuxt-vuetify-variables

1. Clone repository
2. cd nuxt-vuetify-variables
3. npm install
4. npm run dev
5. Open http://localhost:3000/ in browser

**Expected behavior**
h1 - h6 should be display font size of 100px.

**Screenshots**
<img width="1680" alt="スクリーンショット 2020-04-29 1 08 59" src="https://user-images.githubusercontent.com/54343579/80510742-1a81f880-89b6-11ea-8bad-0ce33ef5c58c.png">

**Additional context**
"$font-size-root" is overrided.

![image](https://user-images.githubusercontent.com/54343579/80510953-692f9280-89b6-11ea-8966-f89c020c0889.png)

**Comment by easydrops** [comment]
I stumbled across this myself and was really confused by it, since it is [not well documented](https://vuetifyjs.com/en/styles/typography/#typography).
The `$headings` variable only styles these specific [classes](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/elements/_typography.sass). I suppose they did that to give us the ability to write SEO friendly code.
However with that being said, I personally find the naming convention of these classes counter intuitive and needs some getting used to. For example the class `display-4 ` has a `h1` style applied to it.

**Comment by sktbcbbs** [comment]
@easydrops 
OK.
By default, classes such as `display-4` are not responsive, so I thought it would be a pain to write my own style, but it seems better to use this class.
Thank you very much!!
