### ISSUE TITLE
Please update module to latest vuetify next v2.0.0-beta.9

### ISSUE THREAD

**Issue by manastalukdar** [nuxt-community/vuetify-module#54]

**Comment by kevinmarrec** [comment]
Released update with last Vuetify version & lockfile maintenance.

https://github.com/nuxt-community/vuetify-module/releases
https://www.npmjs.com/package/@nuxtjs/vuetify?activeTab=versions

The Nuxt Vuetify module will now automatically keep in sync with Vuetify 2 Beta.
We're now directly targeting `vuetify@next` dependency instead of specific version, which means you'll not have to wait a new Nuxt module version but you'll have now to maintain your lockfile if you want to upgrade Vuetify to last version.
