### ISSUE TITLE
Problems with icons and pre-made layouts

### ISSUE THREAD

**Issue by velidonmez** [nuxt-community/vuetify-module#74]
I tried to use one of the pre-made layouts in https://vuetifyjs.com/en/getting-started/pre-made-layouts and encountered this problem:

![image](https://user-images.githubusercontent.com/22327527/61877955-b4cd8100-aef8-11e9-85c0-c6fddd31dba2.png)

After refreshing page: 
![image](https://user-images.githubusercontent.com/22327527/61878010-da5a8a80-aef8-11e9-9af9-731e34e27424.png)

Any idea what causes this problem?

**Comment by kevinmarrec** [comment]
@velidonmez It's cause their predefined Layout uses somehow 3 icon presets at the same time (google material design (md), material design icons (mdi) and font awesome (fa)),. Default one is only `mdi-` ones so that's why only these are working (see your screenshot).

You need to change the icons of the snippet by `mdi-` ones to make it work.
So it's no an issue for icons, but your `document is not defined` error seems weird, is it reproducible ? If yes please share a repository with reproduction so I can help you.

**Comment by velidonmez** [comment]
I think this.$vuetify.theme.dark in the created hook causes this problem. You can reproduce it here: https://github.com/velidonmez/vuetify-theme-issue

**Comment by kevinmarrec** [comment]
@velidonmez I think it should be `mounted` and not `created` you're looking for, `created` is called serverSide when using Nuxt `universal` mode, and toggling `this.$vuetify.theme.dark` makes Vuetify reactivity calling a method that need access to `document`, which is something not accessible serverSide.

Furthermore, if you want Vuetify being dark theme by default, you can just do this in your Nuxt configuration file :

```js
vuetify: {
  theme: {
    dark: true
  }
}
```

**Comment by kevinmarrec** [comment]
Closing as non reproducible and all is good at : https://codesandbox.io/s/nuxtjs-vuetify-v0k7i (Mdi icons + dark mode toggle working)
